include ../../global_config

OBJS = $(OBJDIR)/color3way.o  \
	$(OBJDIR)/color3waywindow.o

OUTPUT = $(PLUGIN_DIR)/color3way.plugin

include ../../plugin_config

$(OBJDIR)/color3way.o: color3way.C
$(OBJDIR)/color3waywindow.o: color3waywindow.C
